// ============================================================
// ALMA · TYPES · alma.ts
// ============================================================
// What this file does: Central domain types for the Alma app
// Module: foundation — see modules/foundation/README.md
// Depends on: nothing — these are foundational types
// Used by: all modules, components, and API routes
// Zone: GREEN
// Handoff: NO
// Last checkpoint: PHASE-00
// ============================================================

// ─── TYPES ────────────────────────────────────────────────
// Why: Domain types define the shape of data throughout the app.
// JSDoc comments explain purpose and constraints for each type.

// ─── ENUMS ────────────────────────────────────────────────

/**
 * Available channels for Alma communication.
 * Telegram is the pilot channel. WhatsApp is deferred.
 */
export type MessageChannel = 'in-app' | 'telegram';

/**
 * Alert severity levels determine UI rendering and urgency.
 * Low: inline in feed. Medium: fixed banner. Urgent: full-screen overlay.
 */
export type AlertSeverity = 'low' | 'medium' | 'urgent';

/**
 * Task priority levels for ordering and filtering.
 */
export type TaskPriority = 'low' | 'normal' | 'high';

/**
 * Memory categories for organizing stored knowledge.
 */
export type MemoryCategory =
  | 'preference'
  | 'fact'
  | 'relationship'
  | 'routine'
  | 'health'
  | 'other';

/**
 * Alma interface modes. Elderly mode has simplified UI.
 */
export type AlmaMode = 'standard' | 'elderly';

/**
 * Keys for autonomy settings domains.
 * Each domain has an independent autonomy level 0-100.
 */
export type AutonomyKey = 'messages' | 'calendar' | 'smart_home';

/**
 * Autonomy settings per domain.
 * Values 0-100 determine how independently Alma can act.
 * 0-25: Suggest only (Alma recommends, user decides)
 * 26-50: Ask first (Alma asks before acting)
 * 51-75: Auto + notify (Alma acts, notifies after)
 * 76-100: Fully autonomous (Alma acts silently)
 */
export interface AutonomySettings {
  messages: number;
  calendar: number;
  smart_home: number;
}

// ─── CORE TYPES ───────────────────────────────────────────

/**
 * User profile stored in Supabase.
 * Linked to auth.users via id.
 */
export interface UserProfile {
  /** Primary key, matches auth.users.id */
  id: string;
  /** Display name for greetings and UI */
  display_name: string;
  /** User's preferred timezone (IANA format) */
  timezone: string;
  /** Current interface mode */
  mode: AlmaMode;
  /** Autonomy settings per domain (null means use defaults) */
  autonomy_settings: AutonomySettings | null;
  /** When the profile was created */
  created_at: string;
  /** When the profile was last updated */
  updated_at: string;
}

/**
 * A single message in the Alma chat.
 * Can be from user or assistant (Alma).
 */
export interface AlmaMessage {
  /** Primary key */
  id: string;
  /** Foreign key to user_profiles.id */
  user_id: string;
  /** Message sender: 'user' or 'assistant' */
  role: 'user' | 'assistant';
  /** Message content (plain text or markdown) */
  content: string;
  /** Which channel this message came from */
  channel: MessageChannel;
  /** When the message was created */
  created_at: string;
}

/**
 * A memory stored by Alma about the user.
 * Used for personalization and context.
 */
export interface AlmaMemory {
  /** Primary key */
  id: string;
  /** Foreign key to user_profiles.id */
  user_id: string;
  /** Category for filtering and organization */
  category: MemoryCategory;
  /** The actual memory content */
  content: string;
  /** When this memory was created */
  created_at: string;
  /** When this memory was last accessed or updated */
  updated_at: string;
}

/**
 * A task created by or for the user.
 * Can be created manually or by Alma from conversation.
 */
export interface AlmaTask {
  /** Primary key */
  id: string;
  /** Foreign key to user_profiles.id */
  user_id: string;
  /** Task title/description */
  title: string;
  /** Priority level for ordering */
  priority: TaskPriority;
  /** Whether the task is completed */
  is_completed: boolean;
  /** Optional due date (ISO 8601) */
  due_date: string | null;
  /** When the task was created */
  created_at: string;
  /** When the task was last updated */
  updated_at: string;
}

/**
 * An alert generated by Alma.
 * Alerts require user attention and vary by severity.
 */
export interface AlmaAlert {
  /** Primary key */
  id: string;
  /** Foreign key to user_profiles.id */
  user_id: string;
  /** Alert title */
  title: string;
  /** Alert body/description */
  body: string;
  /** Severity determines UI rendering */
  severity: AlertSeverity;
  /** Whether the user has dismissed this alert */
  is_dismissed: boolean;
  /** When the alert is snoozed until (ISO 8601), null if not snoozed */
  snoozed_until: string | null;
  /** When the alert was created */
  created_at: string;
}

// ─── EXPORTS ──────────────────────────────────────────────
// Re-export all types for convenient importing
